### PR TITLE
Add children's level to teach them how to play.

### PR DESCRIPTION
**Pull request by cdroulers**
Basic children's levels!

### CODE REVIEW

**Review by olafleur — APPROVED** [review]
What a nice idea ! Love it ! :)

**Comment by cdroulers** [comment]
I'll try them on Charlotte ( 5 y/o) soon.

She couldn't get past the second level on her own.

**Comment by cdroulers** [comment]
MERGING!

**Comment by cdroulers** [comment]
Worked super well with Charlotte. She gets the controls and basic logic!

**Pull request merged**
