### PR TITLE
Use Material Design Lite for layout

### LINKED ISSUE #13: Mobile / responsive layout
Material design style. Probably have the game be its own page. Use floating hamburger menu to show controls and level functionality in full page popups that become scrollable.

### PR DESCRIPTION
**Pull request by cdroulers**
Closes #13 and looks good!

### CODE REVIEW

**Comment by olafleur** [comment]
Really nice job ! Love the new look !

Is the overlap of the menu with the game intended when resizing the window (and I guess it would be the same thing on mobile) ?

capture

**Review by olafleur — APPROVED** [review]

**Comment by cdroulers** [comment]
Yes. Maximum screen real estate for the canvas!

On 6 Jan 2017 20:01, "Olivier Lafleur" <notifications@github.com> wrote:

Really nice job ! Love the new look !

Is the overlap of the menu with the game intended ?

[image: capture]
<https://cloud.githubusercontent.com/assets/1068290/21737840/db108820-d44a-11e6-82e8-b01723c44121.PNG>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cdroulers/block-fly/pull/23#issuecomment-271049587>,
or mute
the thread

**Comment by olafleur** [comment]
Great ! :)

**Comment by cdroulers** [comment]
Tested on mobile!

**Pull request merged**
